version: '3.3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - "./docker/mongo_data:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongo12FbKill
    networks:
      - backend
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis_data:/data
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - backend

volumes:
  redis_data:
  mongo_data:
networks:
  backend:
