# === MongoDB ===
quarkus.mongodb.connection-string=mongodb://root:mongo12FbKill@192.168.131.11:27017
quarkus.mongodb.database=geotracker

# === Redis ===
quarkus.redis.hosts=redis://191.168.131.11:6379
quarkus.redis.timeout=PT5S

# === Kafka ===
kafka.bootstrap.servers=192.168.131.11:9092

# Consumer: eventos de localización entrantes
#mp.messaging.incoming.location-events-in.connector=smallrye-kafka
#mp.messaging.incoming.location-events-in.topic=location-events
#mp.messaging.incoming.location-events-in.group.id=geo-tracker-group
#mp.messaging.incoming.location-events-in.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
#mp.messaging.incoming.location-events-in.auto.offset.reset=earliest
mp.messaging.incoming.ordenes.connector=smallrye-kafka
mp.messaging.incoming.ordenes.topic=ordenes
mp.messaging.incoming.ordenes.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer

mp.messaging.incoming.ordenes.bootstrap.servers=192.168.131.11:9092
#mp.messaging.incoming.ordenes.group.id=orden-consumer

# Producer: eventos procesados hacia downstream
mp.messaging.outgoing.location-events-out.connector=smallrye-kafka
mp.messaging.outgoing.location-events-out.topic=location-events-processed
mp.messaging.outgoing.location-events-out.value.serializer=org.apache.kafka.common.serialization.StringSerializer

# === REST ===
quarkus.http.port=8080
quarkus.rest.path=/api

# === OpenAPI ===
quarkus.smallrye-openapi.path=/openapi
quarkus.swagger-ui.always-include=true

# === Logs ===
quarkus.log.level=INFO
quarkus.log.category."com.geotracker".level=DEBUG

